# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywtw_ysLFP4Fy_ERbBc1igzX2_ZqiGDQ
"""

import streamlit as st
import requests
import matplotlib.pyplot as plt

st.title("Orbital Mechanics Simulation")

x = st.slider("Initial X", 6000.0, 8000.0, 7000.0)
y = st.slider("Initial Y", -1000.0, 1000.0, 0.0)
vx = st.slider("Initial Vx", -5.0, 5.0, 0.0)
vy = st.slider("Initial Vy", 5.0, 10.0, 7.5)
steps = st.slider("Simulation Steps", 200, 2000, 1000)


if st.button("Simulate Orbit"):
    response = requests.post(
        "http://127.0.0.1:8000/simulate",
        json={"x": x, "y": y, "vx": vx, "vy": vy, "steps": steps}
    )

    if response.status_code == 200:
        data = response.json()

        fig, ax = plt.subplots()
        circle = plt.Circle((0,0), 6371, color='blue', alpha=0.3)
        ax.add_artist(circle)
        ax.plot(data["x"], data["y"])
        ax.set_aspect('equal')
        ax.set_title("Orbit")
        ax.set_xlabel("X Position (km)")
        ax.set_ylabel("Y Position (km)")
        ax.grid()

        st.pyplot(fig)
    else:
        st.error("API request failed")