# -*- coding: utf-8 -*-
"""orbit_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_EHmlj7heJiK5IqBf-ghzzR59FV5Vii
"""

from fastapi import FastAPI
from pydantic import BaseModel
from orbit import simulate_orbit
import numpy as np

app = FastAPI()

class OrbitInput(BaseModel):
    x: float
    y: float
    vx: float
    vy: float
    steps: int = 1000

@app.get("/")
def root():
    return {"message": "Orbital Simulation API"}

@app.post("/simulate")
def simulate(data: OrbitInput):
    state = np.array([data.x, data.y, data.vx, data.vy])

    positions = simulate_orbit(state, steps=data.steps)

    return {
        "x": positions[:, 0].tolist(),
        "y": positions[:, 1].tolist()
    }