# -*- coding: utf-8 -*-
"""orbital_mechanics_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAnG28I2hBNAXTXjNniwlczL6bgolwdx
"""

import numpy as np

# Earth's gravitational parameter
mu = 398600

def derivatives(state):
    x, y, vx, vy = state
    r = np.sqrt(x**2 + y**2)

    ax = -mu * x / r**3
    ay = -mu * y / r**3

    return np.array([vx, vy, ax, ay])

def simulate_orbit(state, dt=10, steps=2000):
    positions = []

    for _ in range(steps):
        k1 = derivatives(state)
        k2 = derivatives(state + 0.5 * dt * k1)
        k3 = derivatives(state + 0.5 * dt * k2)
        k4 = derivatives(state + dt * k3)

        state = state + (dt / 6) * (k1 + 2*k2 + 2*k3 + k4)

        positions.append(state[:2].copy())

    return np.array(positions)